name: Update README with Most Recent Blog Post

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch recent blog post
        run: |
          RECENT_POST_TITLE=$(curl -s https://sunghj1118.github.io/feed.xml | grep -o '<title>[^<]*</title>' | sed -n '2p' | sed 's/<title>\(.*\)<\/title>/\1/')
          RECENT_POST_LINK=$(curl -s https://sunghj1118.github.io/feed.xml | grep -o '<link>[^<]*</link>' | sed -n '2p' | sed 's/<link>\(.*\)<\/link>/\1/')
          echo "RECENT_POST_TITLE=${RECENT_POST_TITLE}" >> $GITHUB_ENV
          echo "RECENT_POST_LINK=${RECENT_POST_LINK}" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i '/^<!-- MOST_RECENT_POST -->$/c\Most Recent Post: [${RECENT_POST_TITLE}](${RECENT_POST_LINK})' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update most recent blog post'
          git push
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
