name: Update README with Most Recent Blog Post

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: Fetch recent blog post
        id: fetch-post
        run: |
          echo "Fetching the recent blog post..."
          RECENT_POST_TITLE=$(curl -s https://sunghj1118.github.io | xmllint --html --xpath '//div[contains(@class,"pages__PostContainer-sc-1kgpy79-7")]//h3/a[1]/text()' - 2>/dev/null | head -n 1 | xargs)
          RECENT_POST_LINK=$(curl -s https://sunghj1118.github.io | xmllint --html --xpath '//div[contains(@class,"pages__PostContainer-sc-1kgpy79-7")]//h3/a[1]/@href' - 2>/dev/null | sed 's/href="//;s/"//g' | head -n 1 | xargs)
          echo "RECENT_POST_TITLE=${RECENT_POST_TITLE}"
          echo "RECENT_POST_LINK=https://sunghj1118.github.io${RECENT_POST_LINK}"
          echo "::set-output name=post_title::${RECENT_POST_TITLE}"
          echo "::set-output name=post_link::https://sunghj1118.github.io${RECENT_POST_LINK}"

      - name: Check environment variables
        run: |
          echo "Checking environment variables..."
          echo "RECENT_POST_TITLE=${{ steps.fetch-post.outputs.post_title }}"
          echo "RECENT_POST_LINK=${{ steps.fetch-post.outputs.post_link }}"

      - name: Log README before update
        run: |
          echo "Logging README before update..."
          cat README.md

      - name: Update README
        run: |
          echo "Updating README..."
          sed -i '/^<!-- START_RECENT_POST -->$/,/^<!-- END_RECENT_POST -->$/c\<!-- START_RECENT_POST -->\n**Most Recent Post:** [${{ steps.fetch-post.outputs.post_title }}](${{ steps.fetch-post.outputs.post_link }})\n<!-- END_RECENT_POST -->' README.md
          echo "README updated with the most recent post."

      - name: Log README after update
        run: |
          echo "Logging README after update..."
          cat README.md

      - name: Commit changes
        run: |
          echo "Committing changes..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m 'Update most recent blog post' || echo "No changes to commit"
          echo "Changes committed."

      - name: Push changes
        run: |
          echo "Pushing changes..."
          git push https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          echo "Changes pushed."
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
