name: Update README with Most Recent Blog Post

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pup
        run: |
          sudo apt-get update
          sudo apt-get install -y pup

      - name: Fetch recent blog post
        run: |
          echo "Fetching the recent blog post..."
          RECENT_POST_TITLE=$(curl -s https://sunghj1118.github.io | pup 'div.pages__PostContainer-sc-1kgpy79-7 h3 a text{}' | head -n 1)
          RECENT_POST_LINK=$(curl -s https://sunghj1118.github.io | pup 'div.pages__PostContainer-sc-1kgpy79-7 h3 a attr{href}' | head -n 1)
          echo "RECENT_POST_TITLE=${RECENT_POST_TITLE}"
          echo "RECENT_POST_LINK=https://sunghj1118.github.io${RECENT_POST_LINK}"
          echo "RECENT_POST_TITLE=${RECENT_POST_TITLE}" >> $GITHUB_ENV
          echo "RECENT_POST_LINK=https://sunghj1118.github.io${RECENT_POST_LINK}" >> $GITHUB_ENV

      - name: Check environment variables
        run: |
          echo "Checking environment variables..."
          echo "RECENT_POST_TITLE=${RECENT_POST_TITLE}"
          echo "RECENT_POST_LINK=https://sunghj1118.github.io${RECENT_POST_LINK}"

      - name: Update README
        run: |
          echo "Updating README..."
          sed -i '/^<!-- MOST_RECENT_POST -->$/c\Most Recent Post: [${RECENT_POST_TITLE}](https://sunghj1118.github.io${RECENT_POST_LINK})' README.md
          echo "README updated with the most recent post."

      - name: Commit changes
        run: |
          echo "Committing changes..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m 'Update most recent blog post' || echo "No changes to commit"
          echo "Changes committed."

      - name: Push changes
        run: |
          echo "Pushing changes..."
          git push https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          echo "Changes pushed."
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
